### ISSUE TITLE
`AudioContext` not polyfilled

### ISSUE THREAD

**Issue by romainmenke** [mrhenry/core-web#1747]
I also tried this source code, set .browserslistrc to `> 0.1%` and pass browserslist to `babel-plugin-core-web` directly.

```
const audioContext = new AudioContext();
console.log(audioContext);
```

```
plugins: [
	[
		'@mrhenry/core-web',
		{
			browserslist: ['> 0.1%'],
		},
	],
],
```

The added polyfills only includes `@mrhenry/core-web/modules/console.js` and `@mrhenry/core-web/modules/console.log.js`, but due to [my own handling](https://github.com/AnYiEE/AwesomeGadgets/blob/57b5e1e16b11f1393c6d0766af9970bac82a78a6/scripts/modules/babel-plugin-import-polyfills.ts#L73) (using `caniuse-api`), the `audio-context-polyfill/AudioContext.js` is imported, while [this one](https://github.com/mrhenry/core-web/blob/main/packages/core-web/modules/AudioContext.js) in the repo is not.

_Originally posted by @AnYiEE in https://github.com/mrhenry/core-web/issues/1745#issuecomment-1847939827_

**Comment by romainmenke** [comment]
Responding specifically about `AudioContext`.

This polyfill doesn't have any support data : https://github.com/JakeChampion/polyfill-library/blob/master/polyfills/AudioContext/config.toml

So we can not inject it.
This is the only polyfill like that.

You can still manually include the module : `@mrhenry/core-web/modules/AudioContext.js`

**Comment by AnYiEE** [comment]
> This polyfill doesn't have any support data

Maybe can try [this](https://www.npmjs.com/package/caniuse-api) or [this](https://www.npmjs.com/package/caniuse-lite).

**Comment by romainmenke** [comment]
This polyfill and the support data is coming from : https://github.com/JakeChampion/polyfill-library/tree/master/polyfills/AudioContext

It is not our intention to add extra sources.
All work on polyfills from `polyfill-library` should happen in `polyfill-library` :)

--------

> Then use [Babel's method](https://github.com/AnYiEE/AwesomeGadgets/blob/57b5e1e16b11f1393c6d0766af9970bac82a78a6/scripts/modules/babel-plugin-import-polyfills.ts#L103) to detect if polyfill is needed.

This already works, but as I said, we don't inject polyfills based on usage unless there is support data and in this case there is no support data.

**Comment by AnYiEE** [comment]
@romainmenke Thanks for your work.

I think in practical use, it is not very convenient to manually import `@mrhenry/core-web/modules/AudioContext.js` when using `AudioContext`. Especially since browserslist may be changed in the future.

We cannot globally search for where AudioContext is used and add imports when the current browserslist does not support AudioContext. And when the current browserslist supports AudioContext, we have to removing the imports. At this time, it is still necessary to remember the compatibility data of AudioContext.

I believe one of the purposes of using browserslist and plugins is to "automate certain processes". The compatibility data for AudioContext can be found here: https://caniuse.com/?search=AudioContext. Can it be set additionally?

**Comment by romainmenke** [comment]
What I meant was :

- you can use a manual import of the module as a workaround
- you can open an issue or a pull request at https://github.com/JakeChampion/polyfill-library for the data

There really is nothing to do here for us.

Fixing the data issue at the source (`polyfill-library`) means that more people will benefit from that fix. It doesn't make sense to maintain patches here in `core-web`.

**Comment by AnYiEE** [comment]
I will try to submit an issue to the polyfill-library. Thank you very much for your patient response.

**Comment by romainmenke** [comment]
Closing as it can not be resolved here and will automatically be fixed when `polyfill-library` has support data.
